---
jmxUrl: "service:jmx:rmi:///jndi/rmi://kafka-producer:9091/jmxrmi"  # Connect to Kafka's JMX port
username: ""
password: ""
lowercaseOutputName: true
lowercaseOutputLabelNames: true

# Metrics configuration for Kafka
collectDefaultMetrics: true
whitelistObjectNames:
  - "kafka.server:type=BrokerTopicMetrics,name=MessagesInPerSec"
  - "kafka.consumer:type=consumer-fetch-manager-metrics,client-id=*"
  - "kafka.producer:type=producer-metrics,client-id=*"